version: "3.9"

services:
  web:
    build: .
    container_name: outfox_demo_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: outfox_demo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ofpgdata:/var/lib/postgresql/data

volumes:
  ofpgdata: